spring.application.name=eurekaServer

server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false



# =====================================================================
# Logging & Log Rotation Configuration
# =====================================================================
logging.file.name=logs/app-error.log
logging.level.root=INFO
logging.level.com.microservice.ecart.eurekaServer=DEBUG


logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.max-history=7



#===========================================================================

